site_name: Coastline
site_description: A context-aware recommender system for fine-tuning LLMs
site_author: Radu Nicolae, Daniele Lotito, Alexandru Iosup
site_url: https://atlarge-research.github.io/coastline-recommender/
repo_url: https://github.com/atlarge-research/coastline-recommender
repo_name: atlarge-research/coastline-recommender
copyright: MIT License
docs_dir: docs
site_dir: site

nav:
  - Coastline: index.md
  - Usage: usage.md
  - How a recommendation is made: recommendation.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search
